### ISSUE TITLE
Fingerprint works after modifying libfprint

### ISSUE THREAD

**Issue by alaincou** [aigilea/hp_spectre_x360_14_eu0xxx#17]
I am using KDE on Debian Unstable.

Download last library https://gitlab.freedesktop.org/libfprint/libfprint

Add in the c file ./libfprint/drivers/synaptics/synaptics.c
line  " { .vid = SYNAPTICS_VENDOR_ID,  .pid = 0x016C,  },"
Compiled libfprint and replaced /lib/x86_64-linux-gnu/libfprint-2.so.2.0.0

frprintd works!  enroll, verify, pam...

**Comment by christian-bendiksen** [comment]
Great! Have you sent a patch upstream?

**Comment by alaincou** [comment]
> Great! Have you sent a patch upstream?
[No, I just wrote that in (https://gitlab.freedesktop.org/libfprint/libfprint)]

**Comment by n3thshan** [comment]
> > Great! Have you sent a patch upstream?
> > [No, I just wrote that in (https://gitlab.freedesktop.org/libfprint/libfprint)]
Please create a merge request. If it is accepted, users wont have to manually do all of this to get the sensor working. This will also benefit users like me who are using immutable distros who cant do this and test

**Comment by n3thshan** [comment]
i tried creating a merge request and even after requesting permission and getting approval from the freedesktop gitlab, i still dont see the create merge request button. Can anyone help me figure it out?

**Comment by mariusagur** [comment]
> I am using KDE on Debian Unstable.
> 
> Download last library https://gitlab.freedesktop.org/libfprint/libfprint
> 
> Add in the c file ./libfprint/drivers/synaptics/synaptics.c line " { .vid = SYNAPTICS_VENDOR_ID, .pid = 0x016C, }," Compiled libfprint and replaced /lib/x86_64-linux-gnu/libfprint-2.so.2.0.0
> 
> frprintd works! enroll, verify, pam...

How did you build it? I keep getting errors about udev missing, even with udev, libudev-dev and python3-pyudev installed (debian testing)

**Comment by Dadoum** [comment]
I submitted a [merge request](https://gitlab.freedesktop.org/libfprint/libfprint/-/merge_requests/505), it got approved and should be merged soon.

**Comment by n3thshan** [comment]
> I submitted a [merge request](https://gitlab.freedesktop.org/libfprint/libfprint/-/merge_requests/505), it got approved and should be merged soon.

thank you so much for ur contribution! i see it has received approval as of now. is there anything else left for it to be merged?

**Comment by n3thshan** [comment]
@Dadoum hi! whats the update on the merge request? does it need another person's approval to be merged or is it just refusing because of the pipeline error?

**Comment by Dadoum** [comment]
> @Dadoum hi! whats the update on the merge request? does it need another person's approval to be merged or is it just refusing because of the pipeline error?

I think it's due to the pipeline error, but I don't know why it doesn't work. It works on my computer.™

**Comment by n3thshan** [comment]
its not ur fault. As Benjamin said, it will fix itself eventually and then will be merged as soon as the pipeline succeeds since we now have the approval as well! Im not too sure on how MRs work but if u can run the pipeline again and see, maybe miraculously it may work lol

**Comment by n3thshan** [comment]
I made an rpm for the libfprint with support for our fingerprint sensor: https://mega.nz/file/CzZxhQiT#KKKEHRuahvcF2qSnMiogiFSqRKeN3fO-aLjStSlwGWM

**Comment by raymond79nl** [comment]
This sounds promising, but I'm struggling with how to apply this in Arch / Manjaro. Has anybody succeeded on this? If so, would you be willing to share required steps?

**Comment by UnconventionalMindset** [comment]
> This sounds promising, but I'm struggling with how to apply this in Arch / Manjaro. Has anybody succeeded on this? If so, would you be willing to share required steps?

I was struggling too but I managed to fix it so I just published my first ever AUR package:
https://aur.archlinux.org/packages/libfprint-spectre2024-patched-git
You should be able to install it with `yay`:
```
yay -Ss libfprint-spectre2024-patched-git
```
once it's installed, just follow the instructions at https://wiki.archlinux.org/title/Fprint
I do not know if Manjaro supports AUR so I am not sure how to help with that, however the PKGBUILD is almost equivalent to a bash script so if you download from the link above maybe you can figure out how to build libfprint from scratch?

**Comment by raymond79nl** [comment]
Thx @UnconventionalMindset!

AUR is available in Manjaro, so should be able to get this working. The build process is fails after some time though. Any idea what could cause this?

`[137/144] Generating libfprint/FPrint-2.0.gir with a custom command (wrapped by meson to set env)
FAILED: libfprint/FPrint-2.0.gir 
env PKG_CONFIG_PATH=/var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/build/meson-uninstalled PKG_CONFIG=/usr/bin/pkg-config CC=cc /usr/bin/g-ir-scanner --quiet --no-libtool --namespace=FPrint --nsversion=2.0 --warn-all --output libfprint/FPrint-2.0.gir --c-include=fprint.h -I/var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/libfprint/libfprint -I/var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/build/libfprint -I/var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/libfprint/. -I/var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/build/. -I/var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/libfprint/libfprint/nbis/include -I/var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/build/libfprint/nbis/include -I/var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/libfprint/libfprint/nbis/libfprint-include -I/var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/build/libfprint/nbis/libfprint-include --filelist=/var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/build/libfprint/libfprint-2.so.2.0.0.p/FPrint_2.0_gir_filelist -L/var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/build/libfprint --extra-library=fprint-2 --include=Gio-2.0 --include=GObject-2.0 --include=GUsb-1.0 --symbol-prefix=fp_ --identifier-prefix=Fp --pkg-export=fprint --cflags-begin -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_68 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_68 -D_GNU_SOURCE '-DG_LOG_DOMAIN="libfprint"' -I/var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/libfprint/. -I/var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/build/. -I/var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/libfprint/libfprint/nbis/include -I/var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/build/libfprint/nbis/include -I/var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/libfprint/libfprint/nbis/libfprint-include -I/var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/build/libfprint/nbis/libfprint-include -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/gusb-1 -I/usr/include/libusb-1.0 -I/usr/include/json-glib-1.0 -I/usr/include/pixman-1 -I/usr/include/nss -I/usr/include/nspr -I/usr/include/gudev-1.0 -I/usr/include/gobject-introspection-1.0 --cflags-end --add-include-path=/usr/share/gir-1.0 -L/var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/build/libfprint --library fprint-2 --extra-library=gio-2.0 --extra-library=gobject-2.0 --extra-library=glib-2.0 --extra-library=gusb --extra-library=usb-1.0 --extra-library=json-glib-1.0 --extra-library=m --extra-library=pixman-1 --extra-library=ssl3 --extra-library=smime3 --extra-library=nss3 --extra-library=nssutil3 --extra-library=plds4 --extra-library=plc4 --extra-library=nspr4 --extra-library=gudev-1.0 --extra-library=girepository-1.0 --sources-top-dirs /var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/libfprint/ --sources-top-dirs /var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/build/
	not a dynamic executable
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 104, in <module>
    sys.exit(scanner_main(sys.argv))
             ~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/lib/gobject-introspection/giscanner/scannermain.py", line 610, in scanner_main
    shlibs = create_binary(transformer, options, args)
  File "/usr/lib/gobject-introspection/giscanner/scannermain.py", line 434, in create_binary
    shlibs = resolve_shlibs(options, binary, options.libraries)
  File "/usr/lib/gobject-introspection/giscanner/shlibs.py", line 170, in resolve_shlibs
    _resolve_non_libtool(options, binary, non_libtool))
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/gobject-introspection/giscanner/shlibs.py", line 106, in _resolve_non_libtool
    output = subprocess.check_output(args)
  File "/usr/lib/python3.13/subprocess.py", line 472, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
               **kwargs).stdout
               ^^^^^^^^^
  File "/usr/lib/python3.13/subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ldd', '/var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/build/tmp-introspectvcfagvct/FPrint-2.0']' returned non-zero exit status 1.
[138/144] Linking target tests/test-fpi-device
[139/144] Linking target libfprint/fprint-list-udev-hwdb
[140/144] Linking target tests/test-fpi-ssm
[141/144] Linking target libfprint/fprint-list-udev-rules
[142/144] Linking target libfprint/fprint-list-supported-devices
ninja: build stopped: subcommand failed.
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /var/tmp/pamac-build-raymond/libfprint-spectre2024-patched-git/src/build
==> ERROR: A failure occurred in build().
    Aborting...
`

**Comment by Dadoum** [comment]
Merged! 🎉

**Comment by n3thshan** [comment]
Finally! thanks @Dadoum for ur contribution! now all we have to do is wait for a couple of more months for a release.

**Comment by alaincou** [comment]
Great,
On debian testing, today a new version of fprintd with the update that works on my HP-14 Spectre.
Just install fprintd (included libfprint-2-2 in the latest version 1.94.9 which contains the modification) and libpam-fprintd.

Normally, this should arrive very quickly on all Stable Linux distributions.
Thanks again to all and especially Dadoum

**Comment by n3thshan** [comment]
https://packages.fedoraproject.org/pkgs/libfprint/libfprint/

heres the fedora tracker for anyone eagerly waiting

**Comment by alaincou** [comment]
Hello @n3thshan 

I think that before closing it would be necessary to modify the sentence in Readme "Synaptics releases Linux-compatible firmware only if requested by the vendor so fingerprint reader won't work without HP say-so (none of previous generations got one working)."

Overall, on the problems on HP 14-eu000 would remain only the cameras:
OVTI08F4 (ov08x40) which has a linux driver but does not work
OVTI00AB (og0va1b) without linux driver
TXNW3643 Led Torch for IR Camera (lm3643) which with og0va1b (Under Windows we see the led light up in red on the left)
But these are other subjects

**Comment by n3thshan** [comment]
> I think that before closing it would be necessary to modify the sentence in Readme "Synaptics releases Linux-compatible firmware only if requested by the vendor so fingerprint reader won't work without HP say-so (none of previous generations got one working)."

i think the maintainer of this repo is not active anymore but ill create a PR nevertheless and see if itll work

**Comment by Dadoum** [comment]
> https://packages.fedoraproject.org/pkgs/libfprint/libfprint/
> 
> heres the fedora tracker for anyone eagerly waiting
> 
> With that said i think we can close this issue as complete right? [@alaincou](https://github.com/alaincou)

The Fedora update is now available 🎉
